---

- name: "Create a network"
  docker_network:
    name: "{{ docker_network_name }}"

- name: "Container for app"
  docker_container:
    name: "app"
    image: "{{ docker_repo }}/{{ image_app }}:{{ tag_app2 }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network_name }}"

- name: "Container for app2"
  docker_container:
    name: "app2"
    image: "{{ docker_repo }}/{{ image_app2 }}:{{ tag_app2 }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network_name }}"